services:
  db:
    container_name: sqlite_locale
    image: nouchka/sqlite3:latest
    volumes: 
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3

  sqlite-web:
    container_name: sqlite_webview_locale
    image: coleifer/sqlite-web
    volumes:
      - ./backend:/data
    ports:
      - 8080:8080
    environment:
      - SQLITE_WEB_PASSWORD=local
    command: sqlite_web -H 0.0.0.0 -x db.sqlite3 --password
    depends_on:
      - db

  backend:
    container_name: backend_locale
    build:
      context: backend/.
      dockerfile: Dockerfile
    command: gunicorn --workers=2 --timeout 120 --bind 0.0.0.0:5000 src.wsgi:application
    volumes: 
      - ./backend:/backend
    # expose:
    #   - "5000"  # Expose the backend instead of binding it to host
    ports:
    - "5000:5000"
    cpus: "1.0"
    mem_limit: 512m
    mem_reservation: 256m
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=demo.experiencebylocals.com localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://demo.experiencebylocals.com

  frontend:
    container_name: frontend_locale
    build:
      context: frontend/.
      dockerfile: Dockerfile
    environment:
      - BACKEND_API_PORT=${BACKEND_API_PORT}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

