# Generated by Django 5.0 on 2025-04-23 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alloweddm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweddm',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alloweddm',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
