# Generated by Django 5.0 on 2025-05-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_event_latitude_event_longitude_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='general.eventtags'),
        ),
    ]
