# Generated by Django 5.0 on 2025-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_booking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
