# Generated by Django 5.0 on 2025-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
