# Generated by Django 5.0 on 2025-05-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_customuser_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('apple', 'Apple'), ('meta', 'Facebook/Instagram')], default='local', max_length=20),
        ),
    ]
