# Generated by Django 5.0 on 2025-05-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_event_external_booking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
